[package]
name = "turbosearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
fltk = "1.3.8"
glob = "0.3.1"
regex = "1.9.6"
walkdir = "2.4.0"

